# Navigation
h j k l   : Select pane
C-h / C-l : Prev/next window
C-j       : Choose tree
9 / 0     : Prev/next session

# Windows & Panes
c         : New window
-         : Split horiz
\         : Split vert
J         : Join horiz
H         : Join vert
t         : Tiled layout
y         : Sync panes

# Resize (no prefix)
S-arrows  : Resize ±2
C-arrows  : Resize ±10

# Tools
u         : URLs (fzf)
r         : Reload config
/         : Help
